"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Sensitive values are read from environment variables so they are never
# hardcoded in source control. Copy backend/.env.example to backend/.env
# and fill in the values for local development.
SECRET_KEY = os.environ["SECRET_KEY"]

# Defaults to False so production environments are safe unless explicitly enabled.
DEBUG = os.environ.get("DEBUG", "False") == "True"

# In production, set this to your domain(s), e.g. "myapp.com,www.myapp.com".
_allowed = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]

# Custom user model — must be set before any migration that references User.
AUTH_USER_MODEL = "users.User"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Django defaults...
    "rest_framework",
    # Generates OpenAPI 3.0 schema and serves Swagger UI / ReDoc.
    "drf_spectacular",
    # Token blacklist allows refresh tokens to be invalidated on logout.
    # Without this, a stolen refresh token could never be revoked before expiry.
    "rest_framework_simplejwt.token_blacklist",
    "users",
    "wayoom_bot",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Set DB_NAME (and other DB_* vars) in .env to use PostgreSQL; otherwise SQLite is used.

if os.environ.get("DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ["DB_NAME"],
            "USER": os.environ.get("DB_USER", ""),
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
            "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
            "PORT": os.environ.get("DB_PORT", "5432"),
            "OPTIONS": {"options": "-c timezone=utc"},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Django REST Framework — global defaults applied to every view.
# Individual viewsets can override these with their own permission_classes list.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # JWT is the primary auth method for the frontend.
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        # Session auth is kept so the Django admin panel and the browsable
        # API continue to work without a token.
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        # Unauthenticated users may read public content; writes always need a login.
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    # Tells DRF to use drf-spectacular's schema generator for every view,
    # so the auto-generated OpenAPI doc stays in sync with the live API.
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# SimpleJWT token lifetimes and rotation policy.
# - Access tokens are short-lived (15 min) to limit the damage of a leaked token.
# - Refresh tokens last 7 days; each use rotates to a fresh token and blacklists
#   the old one, so a stolen refresh token becomes useless after one rotation.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Metadata displayed at the top of the Swagger UI and ReDoc pages.
# SERVE_INCLUDE_SCHEMA=False hides the raw /api/schema/ endpoint from
# its own documentation to avoid a confusing self-referential entry.
SPECTACULAR_SETTINGS = {
    "TITLE": "WayOom Bot API",
    "DESCRIPTION": "REST API for managing flashcard decks and cards.",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
