# Generated by Django 6.0.3 on 2026-03-06 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['deck', '-created_at'], name='wayoom_card_deck_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['user', '-created_at'], name='wayoom_deck_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deck',
            index=models.Index(fields=['is_public', '-created_at'], name='wayoom_deck_public_created_idx'),
        ),
    ]
