# Generated by Django 6.0.3 on 2026-03-08 00:15

import wayoom_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0002_card_wayoom_card_deck_created_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name',
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.JSONField(blank=True, default=list, validators=[wayoom_bot.models.validate_tag_list]),
        ),
    ]
