# Generated by Django 6.0.3 on 2026-03-08 02:36

import wayoom_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0003_remove_card_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='extra_notes',
            field=models.JSONField(blank=True, default=list, validators=[wayoom_bot.models.validate_extra_notes]),
        ),
    ]
