# Generated by Django 6.0.3 on 2026-03-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0004_add_card_extra_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('basic_reversed', 'Basic (Reversed)'), ('cloze', 'Cloze')], default='basic', max_length=20),
        ),
    ]
