# Generated by Django 6.0.3 on 2026-03-08 02:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0005_add_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
