# Generated by Django 6.0.3 on 2026-03-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0006_allow_blank_card_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='card',
            name='interval',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='lapse_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('learning', 'Learning'), ('review', 'Review'), ('suspended', 'Suspended'), ('buried', 'Buried')], default='new', max_length=20),
        ),
    ]
