# Generated by Django 6.0.3 on 2026-03-08 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0007_add_sr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='flag',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
