# Generated by Django 6.0.3 on 2026-03-09 21:29

import django.db.models.deletion
import uuid
import wayoom_bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayoom_bot', '0008_add_card_flag_and_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=wayoom_bot.models._deck_media_upload_path)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='wayoom_bot.deck')),
            ],
            options={
                'indexes': [models.Index(fields=['deck', 'original_filename'], name='wayoom_dm_deck_fname_idx')],
                'constraints': [models.UniqueConstraint(fields=('deck', 'original_filename'), name='wayoom_deckmedia_deck_filename_uniq')],
            },
        ),
    ]
